name: auto-test
on:
  push:
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.0
  test:
    name: test
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v4
        with:
          go-version: 1.21
      - uses: actions/checkout@v1
      - run: go mod download
      - run: go test -cover ./...
